### ISSUE TITLE
SCALE / Apply scale

### ISSUE THREAD

**Issue by lucianomunoz** [julienduroure/FootRollBreak#1]
If you enlarge or shrink down the rig by something like 10 times and apply scales then it breaks the foot, i have a file to show you, one could maybe remove the foot break and then apply it again, or just work with the scale just like the rest of the rigify rig works =)

**Comment by julienduroure** [comment]
Hello,
Is it a Human or Pitchipoy rig ?
Did you scale on object mode, and apply scale, or on pose mode, and set as rest pose ?

Yes, please send me your file, will be more easy to understand :)

**Comment by lucianomunoz** [comment]
Ill send it to you, its human metarig
let me find that file.

**Comment by julienduroure** [comment]
OK, seems I can close this for now.
Don't hesitate to come back to me if you have more info.
